---
- name: Create Argo CD application in OpenShift GitOps
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Same kubeconfig you use for the install role
    ocp_kubeconfig: "/tmp/ocp-cluster-automation.config"

    # Argo CD / GitOps instance details
    ocp_gitops_instance_namespace: "openshift-gitops"  # where ArgoCD & Applications live
    ocp_gitops_instance_name: "openshift-gitops"

    # Application-specific parameters
    argocd_app_name: "minimal-rest-api-framework-git"
    argocd_app_project: "default"

    # Git repo that Argo CD will track
    argocd_repo_url: "https://bitbucket.org/uconnbitbucket/minimalapi-argo.git"
    argocd_repo_path: "."          # path within repo (e.g. "overlays/dev")
    argocd_repo_revision: "main"   # branch, tag, or commit

    # Where to deploy the manifests
    argocd_dest_server: "https://kubernetes.default.svc"
    argocd_dest_namespace: "its-ssg"

    # Sync policy toggles
    argocd_sync_policy_automated: true
    argocd_sync_policy_prune: true
    argocd_sync_policy_selfHeal: true

  roles:
    - ocp_gitops_app
